# Generated by Django 4.2.5 on 2023-09-29 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('company_unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('ceo_name', models.CharField(max_length=255)),
                ('ceo_email', models.EmailField(max_length=255)),
                ('country', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('postcode', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='pictures/no_image.jpg', upload_to='pictures/')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CrmContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('display_name', models.CharField(max_length=255)),
                ('decision_maker', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=255)),
                ('birthdate', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=10)),
                ('foreign_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.account')),
            ],
        ),
    ]
